# Generated by Django 5.2.16 on 2026-07-15 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0001_initial'),
        ('shared', '0005_paciente_sexo_paciente_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eapb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='shared.eapb'),
        ),
    ]
