# Generated by Django 5.2.16 on 2026-07-15 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0002_evento_eapb'),
        ('shared', '0007_paciente_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cie10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='shared.cie10'),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
