# Generated by Django 5.2.16 on 2026-07-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0003_evento_cie10_evento_hora_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado_conciencia',
            field=models.CharField(blank=True, choices=[('ALERTA', 'Alerta'), ('NO ALERTA', 'No Alerta')], max_length=10, null=True),
        ),
    ]
