# Generated by Django 5.2.16 on 2026-07-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0004_evento_estado_conciencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='clasificacion_riesgo_gestacional',
            field=models.CharField(blank=True, choices=[('NO APLICA', 'No Aplica'), ('BAJO', 'Bajo'), ('ALTO', 'Alto'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='clasificacion_riesgo_preeclampsia',
            field=models.CharField(blank=True, choices=[('NO APLICA', 'No Aplica'), ('BAJO', 'Bajo'), ('ALTO', 'Alto'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado')], max_length=25, null=True),
        ),
    ]
