# Generated by Django 5.2.16 on 2026-07-15 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0005_evento_clasificacion_riesgo_gestacional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoMadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destino Madre',
                'verbose_name_plural': 'Destinos Madre',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='diagnostico_ingreso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='destino_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='riamp.destinomadre'),
        ),
    ]
