# Generated by Django 5.2.16 on 2026-07-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0006_destinomadre_evento_diagnostico_ingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTerminacionGestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Terminación Gestación',
                'verbose_name_plural': 'Tipos Terminación Gestación',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_terminacion_gestacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_terminacion_gestacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='riamp.tipoterminaciongestacion'),
        ),
    ]
