# Generated by Django 5.2.16 on 2026-07-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0007_tipoterminaciongestacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoAnticonceptivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método Anticonceptivo',
                'verbose_name_plural': 'Métodos Anticonceptivos',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_suministro_metodo_anticonceptivo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
