# Generated by Django 5.2.16 on 2026-07-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0008_metodoanticonceptivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionAnticoncepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Observación Anticoncepción',
                'verbose_name_plural': 'Observaciones Anticoncepción',
            },
        ),
    ]
