# Generated by Django 5.2.16 on 2026-07-15 03:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0009_observacionanticoncepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='edad_gestacional_rn',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='REGISTRE LA EDAD GESTACIONAL EN SEMANAS DEL RECIÉN NACIDO POR CAPURRO Y/O BALLARD'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_lactancia_materna',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE ATENCIÓN EN SALUD PARA LA PROMOCIÓN Y APOYO DE LA LACTANCIA MATERNA'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_resultado_pr_sifilis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_resultado_vih',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='metodo_anticonceptivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='riamp.metodoanticonceptivo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_nacidos_vivos',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='REGISTRE EL NÚMERO DE RECIÉN NACIDOS VIVOS'),
        ),
        migrations.AddField(
            model_name='evento',
            name='observacion_anticoncepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='riamp.observacionanticoncepcion'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tamizaje_sifilis',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='TAMIZAJE PARA SÍFILIS SEGÚN GPC SÍFILIS HOSPITALARIA'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tamizaje_vih',
            field=models.CharField(blank=True, choices=[('REACTIVO', 'Reactivo'), ('NO REACTIVO', 'No Reactivo'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='TAMIZAJE  PARA VIH INTRAPARTO SEGÚN GPC'),
        ),
    ]
