# Generated by Django 5.2.16 on 2026-07-15 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0010_evento_edad_gestacional_rn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='numero_nacidos_vivos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='REGISTRE EL NÚMERO DE RECIÉN NACIDOS VIVOS'),
        ),
    ]
