# Generated by Django 5.2.16 on 2026-07-15 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0011_alter_evento_numero_nacidos_vivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='edad_gestacional_rn',
        ),
        migrations.CreateModel(
            name='Neonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('peso', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(6000)], verbose_name='Peso al nacer (gramos)')),
                ('talla', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(60)], verbose_name='Talla al nacer (cm)')),
                ('edad_gestacional_rn', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='REGISTRE LA EDAD GESTACIONAL EN SEMANAS DEL RECIÉN NACIDO POR CAPURRO Y/O BALLARD')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neonatos', to='riamp.evento')),
            ],
            options={
                'verbose_name': 'Neonato',
                'verbose_name_plural': 'Neonatos',
            },
        ),
    ]
