# Generated by Django 5.2.16 on 2026-07-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0012_remove_evento_edad_gestacional_rn_neonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='neonato',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Calculado automáticamente a partir de peso y talla.', max_digits=5, null=True, verbose_name='IMC'),
        ),
    ]
