# Generated by Django 5.2.16 on 2026-07-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0013_neonato_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='neonato',
            name='num_certificado_nacimiento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de certificado de nacimiento'),
        ),
    ]
