# Generated by Django 5.2.16 on 2026-07-15 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0014_neonato_num_certificado_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='neonato',
            name='clasificacion_peso_nacer',
            field=models.CharField(blank=True, choices=[('BAJO PESO AL NACER', 'Bajo Peso al Nacer'), ('EN RIESGO BAJO PESO', 'En Riesgo Bajo Peso'), ('PESO ADECUADO', 'Peso Adecuado'), ('MACROSÓMICO', 'Macrosómico'), ('REVISAR PESO AL NACER', 'Revisar Peso al Nacer')], editable=False, max_length=30, null=True, verbose_name='Clasificación del peso al nacer'),
        ),
        migrations.AlterField(
            model_name='neonato',
            name='peso',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(6000)], verbose_name='Peso al nacer (gramos)'),
        ),
    ]
