# Generated by Django 5.2.16 on 2026-07-15 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0015_neonato_clasificacion_peso_nacer_alter_neonato_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neonato',
            name='peso',
            field=models.PositiveSmallIntegerField(default=3000, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(6000)], verbose_name='Peso al nacer (gramos)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neonato',
            name='talla',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(60)], verbose_name='Talla al nacer (cm)'),
            preserve_default=False,
        ),
    ]
