# Generated by Django 5.2.16 on 2026-07-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0016_alter_neonato_peso_alter_neonato_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='neonato',
            name='aplicacion_vitamina_k',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('NO APLICA', 'No Aplica')], max_length=10, null=True, verbose_name='APLICACIÓN DE VITAMINA K'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_reporte_tsh_rn',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE REPORTE DE RESULTADO TSH RN'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tsh_rn',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TOMA DE MUESTRA PARA TSH RN'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_vacunacion_bcg',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE VACUNACIÓN BCG'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_vacunacion_hepatitis_b',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE VACUNACIÓN HEPATITIS B'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tsh_rn',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TSH RN'),
        ),
    ]
