# Generated by Django 5.2.16 on 2026-07-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riamp', '0017_neonato_aplicacion_vitamina_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neonato',
            name='fecha_egreso_recien_nacido',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE EGRESO DEL RECIÉN NACIDO'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_auditivo',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE AUDITIVO'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_cardiopatia',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE CARDIOPATÍA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_deficiencia_biotinidasa',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE DEFICIENCIA DE BIOTINIDASA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_fenilcetonuria',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE FENILCETONURIA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_fibrosis_quistica',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE FIBROSIS QUÍSTICA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_galactosemia',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE GALACTOSEMIA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_hemoglobinopatias',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE HEMOGLOBINOPATÍAS'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='fecha_tamizaje_hiperplasia_suprarrenal',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE TAMIZAJE HIPERPLASIA SUPRARRENAL'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_auditivo',
            field=models.CharField(blank=True, choices=[('PASA', 'Pasa'), ('NO PASA', 'No Pasa'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE AUDITIVO'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_cardiopatia',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE CARDIOPATÍA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_deficiencia_biotinidasa',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE DEFICIENCIA DE BIOTINIDASA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_fenilcetonuria',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE FENILCETONURIA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_fibrosis_quistica',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE FIBROSIS QUÍSTICA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_galactosemia',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE GALACTOSEMIA'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_hemoglobinopatias',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE HEMOGLOBINOPATÍAS'),
        ),
        migrations.AddField(
            model_name='neonato',
            name='resultado_tamizaje_hiperplasia_suprarrenal',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('RIESGO NO EVALUADO', 'Riesgo No Evaluado'), ('NO APLICA', 'No Aplica')], max_length=25, null=True, verbose_name='RESULTADO TAMIZAJE HIPERPLASIA SUPRARRENAL'),
        ),
    ]
