# Generated by Django 5.2.16 on 2026-07-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eapb',
            name='codigo',
            field=models.CharField(default='', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
