# Generated by Django 5.2.16 on 2026-07-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_eapb_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eapb',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
