# Generated by Django 5.2.16 on 2026-07-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_eapb_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name': 'CIE10',
                'verbose_name_plural': 'CIE10',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
