# Generated by Django 5.2.16 on 2026-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_cie10_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PE', 'Permiso Especial de Permanencia')], max_length=2, null=True),
        ),
    ]
