# Generated by Django 5.2.16 on 2026-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_paciente_sexo_paciente_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
