# Generated by Django 5.2.16 on 2026-07-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_paciente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='zona',
            field=models.CharField(blank=True, choices=[('R', 'Rural'), ('U', 'Urbana')], max_length=1, null=True),
        ),
    ]
